general:
  none_threshold: 0.9
  kfolds: 5
features:
  REGION:
    type: Categorical
    fillna: NEW_VALUE
    methods:
      - one_hot_encode
  TENURE:
    type: Categorical
    fillna: NEW_VALUE
    # Reason: 94.8% rows have one value ("K > 24 month")
    methods:
      - drop
  TOP_PACK:
    type: Categorical
    fillna: NEW_VALUE
    methods:
      - one_hot_encode
  DATA_VOLUME:
    type: Numerical
    fillna: MEDIAN
    methods:
      - standard_scale
  REVENUE:
    type: Numerical
    fillna: MEDIAN
    methods:
      - standard_scale
  ARPU_SEGMENT:
    type: Numerical
    fillna: MEDIAN
    methods:
      - standard_scale
  ON_NET:
    type: Numerical
    fillna: MEDIAN
    methods:
      - standard_scale
  MONTANT:
    type: Numerical
    fillna: MEDIAN
    methods:
      - standard_scale
  ORANGE:
    type: Numerical
    fillna: MEDIAN
    methods:
      - standard_scale
  TIGO:
    type: Numerical
    fillna: MEDIAN
    methods:
      - standard_scale
  ZONE1:
    type: Numerical
    fillna: MEDIAN
    # Reason: 93.6% None values
    methods:
      - drop
  ZONE2:
    type: Numerical
    fillna: MEDIAN
    # Reason: 92.1% None values
    methods:
      - drop
  FREQ_TOP_PACK:
    type: Numerical
    fillna: MEDIAN
    methods:
      - standard_scale
  FREQUENCE_RECH:
    type: Numerical
    fillna: MEDIAN
    methods:
      - standard_scale
  FREQUENCE:
    type: Numerical
    fillna: MEDIAN
    methods:
      - standard_scale
  REGULARITY:
    type: Numerical
    fillna: MEDIAN
    methods:
      - standard_scale
  MRG:
    # Reason: constant feature
    methods:
      - drop
train:
  algorithm: cat_boost
  target: CHURN
  n_rows: .1
  random_state: 146
  skip:
    - user_id
    - kfold
  params:
    n_estimators: 1000
    random_state: 42
    verbose: 0
predict:
  models:
    - ./models/2021-11-13T12-51-fold-0.pkl
    - ./models/2021-11-13T12-51-fold-1.pkl
    - ./models/2021-11-13T12-51-fold-2.pkl
    - ./models/2021-11-13T12-51-fold-3.pkl
    - ./models/2021-11-13T12-51-fold-4.pkl